# Generated by Django 5.1 on 2024-09-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_products_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='good s_images', verbose_name='Изображение'),
        ),
    ]
